# Generated by Django 5.1.5 on 2025-02-03 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_customuser_otp_created_at_alter_customuser_groups_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('Student', 'Student'), ('HostelOwner', 'Hostel Owner'), ('Admin', 'Admin')], default='Student', max_length=50),
        ),
    ]
