# Generated by Django 5.1.6 on 2025-03-20 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_customuser_profile_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='unread_messages',
            field=models.IntegerField(default=0),
        ),
    ]
