# Generated by Django 5.1.6 on 2025-03-20 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hostel_owner', '0003_chatmessage'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='hostelimage',
            options={'ordering': ['position']},
        ),
        migrations.AlterModelOptions(
            name='roomimage',
            options={'ordering': ['position']},
        ),
        migrations.AddField(
            model_name='hostelimage',
            name='position',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='roomimage',
            name='position',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
