# Generated by Django 5.1.6 on 2025-03-20 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hostel_owner', '0004_alter_hostelimage_options_alter_roomimage_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='hostel',
            name='cancellation_policy',
            field=models.JSONField(default=dict),
        ),
    ]
