# Generated by Django 5.1.6 on 2025-03-27 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hostel_owner', '0011_alter_room_room_number_alter_room_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='pidx',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
