# Generated by Django 5.1.6 on 2025-04-02 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hostel_owner', '0016_alter_feedback_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='hostel',
            name='is_verified',
            field=models.BooleanField(default=False),
        ),
    ]
