# Generated by Django 5.1.6 on 2025-04-09 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hostel_owner', '0019_chatmessage_image_alter_chatmessage_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='hostel',
            name='latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='hostel',
            name='longitude',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
