# Generated by Django 5.1.6 on 2025-04-02 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userreport',
            name='reason',
            field=models.TextField(default='General complaint'),
        ),
    ]
