# Generated by Django 5.1.6 on 2025-04-07 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0003_blog_contactmessage'),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutUs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('services', models.TextField(help_text='Comma-separated list of services')),
                ('image1', models.ImageField(blank=True, null=True, upload_to='about_us/')),
                ('image2', models.ImageField(blank=True, null=True, upload_to='about_us/')),
                ('image3', models.ImageField(blank=True, null=True, upload_to='about_us/')),
                ('image4', models.ImageField(blank=True, null=True, upload_to='about_us/')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
